#include <math.h>
#include <time.h>
#include <stdlib.h>
#include "./libs/grid.c"
#include "./libs/consts.h"
#include "./libs/numString.c"
#include "./libs/fileManip.c"
#include "./libs/numberWords.c"
#include "./libs/calendar.c"
